---
- hosts: localhost
  connection: local
  become: true


  tasks:
  - name: install additional tools
    package:
      name: 
        - htop
        - tmux
        - net-tools
        - libgl1-mesa-glx
        - libegl1-mesa
        - libxcb-xtest0
        - xfce4
        - xfwm4
        - zsh
        - zsh-doc
        - zsh-syntax-highlighting
        - libreoffice
        - build-essential
        - checkinstall
        - ubuntu-make
        - libreadline-gplv2-dev
        - libncursesw5-dev
        - libssl-dev
        - libsqlite3-dev
        - tk-dev
        - libgdbm-dev
        - libc6-dev
        - libbz2-dev
        - libz-dev
        - libssl-dev
        - libcurl4-gnutls-dev
        - libexpat1-dev
        - gettext
        - cmake
        - gcc
        - remmina
        - terminator

  - name: Add Apt signing key
    apt_key:
      url: "https://dl.google.com/linux/linux_signing_key.pub"
      state: present

  - name: Add repository into sources list
    apt_repository:
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
      state: present
      filename: google-chrome

  - name: Install google-chrome-stable
    apt:
      name: "google-chrome-stable"
      state: latest
      update_cache: true

  - name: Install MatterMost
    apt:
      deb: https://releases.mattermost.com/desktop/5.0.2/mattermost-desktop-5.0.2-linux-amd64.deb

  - name: Install code
    command: snap install code --classic

  - name: Install sublime
    command: snap install sublime-text --classic

